---
- name: Ansible-homelab
  hosts: b550m
  become: true
  gather_facts: true

  vars:
    prometheus_version: 2.46.0
    alertmanager_version: 0.25.0
    node_exporter_version: 1.6.1
    grafana_version: 10.0.3

  roles:
<<<<<<< HEAD
    - traefik
    - cloudflared
    - echo-server
    - syncthing
    - vaultwarden
    - prometheus.prometheus.prometheus
    - prometheus.prometheus.alertmanager
    - prometheus.prometheus.node_exporter
    - grafana.grafana.grafana
    - ome.cadvisor
=======
    # - traefik
    # - cloudflared
    # - echo-server
    # - syncthing
    # - vaultwarden
    - prometheus.prometheus.prometheus
>>>>>>> a181389aa665008ccb90b95c0b157e75229a2a60
