---
- name: Ansible-homelab
  hosts: b550m
  become: true
  gather_facts: true

  vars_files:
    - vars/main.yml
    - inventory/group_vars/all.yml

  tasks:
    - name: Install mysql server
      ansible.builtin.include_role:
        name: geerlingguy.mysql

    - name: Create openvpn server
      ansible.builtin.include_role:
        name: robertdebock.openvpn
      vars:
        openvpn_role: "server"

  # roles:
  #   - cloudflared
  #   - echo-server
  #   - syncthing
  #   - vaultwarden
