---
- name: Update apt-cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600 # Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  register: result
  until: result is succeeded

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: yes
    # state: latest
  # tags:
  #   - skip_ansible_lint

- name: Install Packages
  ansible.builtin.apt:
    name: "{{ item }}"
    install_recommends: false
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - htop
    - iputils-ping
    - lm-sensors
    - neofetch
    - net-tools
    - nfs-common
    - nvme-cli
    - open-iscsi
    - python3
    - python3-apt
    - python3-docker
    - python3-yaml
    - software-properties-common
    - unzip
    - util-linux
  register: result
  until: result is succeeded

- name: Create homelab network
  community.docker.docker_network:
    name: homelab
  register: result
  until: result is succeeded

# - name: Install Loki plugin
#   community.docker.docker_plugin:
#     plugin_name: grafana/loki-docker-driver
#     state: present

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ ansible_hostname }}"

- name: Update hosts
  ansible.builtin.copy:
    content: |
      127.0.0.1 localhost
      127.0.1.1 {{ ansible_hostname }}
      # The following lines are desirable for IPv6 capable hosts
      ::1     localhost ip6-localhost ip6-loopback
      ff02::1 ip6-allnodes
      ff02::2 ip6-allrouters
    dest: /etc/hosts
    mode: preserve

- name: Disable apparmor
  ansible.builtin.systemd:
    name: apparmor
    state: stopped
    masked: true

- name: Disable swap
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop: ["none", "swap"]
