---
grafana_enabled: true
grafana_url: "http://192.168.50.3:3000"
grafana_analytics:
  reporting_enabled: false
grafana_datasources:
  - name: "Prometheus"
    type: "prometheus"
    url: "http://localhost:9090"
    isDefault: true
grafana_dashboards:
  - dashboard_id: '4271'
    revision_id: '3'
    datasource: 'Prometheus'
  - dashboard_id: '1860'
    revision_id: '2'
    datasource: 'Prometheus'
  - dashboard_id: '358'
    revision_id: '1'
    datasource: 'Prometheus'
