---
- name: Music_download Docker Container
  community.docker.docker_container:
    name: music_download
    image: registry.cn-hangzhou.aliyuncs.com/music_downloader/qq_flac_music_downloader
    pull: true
    networks:
      - name: homelab
    volumes:
      - "{{ music_directory }}://workspace/music:rw"
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.gzip.compress: "true"
      traefik.http.routers.music-download.middlewares: "gzip"
      traefik.http.routers.music-download.rule: "Host(`music-download.{{ domain_name }}`)"
      traefik.http.routers.music-download.entrypoints: "websecure"
      traefik.http.routers.music-download.tls.certresolver: "myresolver"
      # traefik.http.routers.music-download.tls.domains[0].main: "{{ domain_name }}"
      # traefik.http.routers.music-download.tls.domains[0].sans: "*.{{ domain_name }}"
      traefik.http.services.music-download.loadbalancer.server.port: "8899"
    restart_policy: unless-stopped
