---
- name: Create mattermost Directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "2000"
    group: "2000"
    mode: "0755"
  with_items:
    - "{{ mattermost_data_directory }}"
    - "{{ mattermost_data_directory }}/db"
    - "{{ mattermost_data_directory }}/config"
    - "{{ mattermost_data_directory }}/data"
    - "{{ mattermost_data_directory }}/logs"
    - "{{ mattermost_data_directory }}/plugins"
    - "{{ mattermost_data_directory }}/client"
    - "{{ mattermost_data_directory }}/client/plugins"
    - "{{ mattermost_data_directory }}/bleve-indexes"

- name: Mattermost db Docker Container
  community.docker.docker_container:
    name: mattermost-db
    image: postgres:15-alpine
    networks:
      - name: homelab
    env:
      TZ: "{{ timezone }}"
      POSTGRES_PASSWORD: "{{ mattermost_db_password }}"
      POSTGRES_USER: "{{ mattermost_db_user }}"
      POSTGRES_DB: "mattermost"
    volumes:
      - "{{ mattermost_data_directory }}/db:/var/lib/postgresql/data"
    security_opts:
      - "no-new-privileges:true"
    pids_limit: 100
    read_only: true
    tmpfs:
      - "/tmp"
      - "/var/run/postgresql"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "mattermost"]
      interval: 10s
      start_period: 30s
    restart_policy: unless-stopped

- name: Mattermost Docker Container
  community.docker.docker_container:
    name: mattermost
    image: mattermost/mattermost-team-edition:7.10.3
    networks:
      - name: homelab
    # ports:
    #   - "18443:8443/udp"
    security_opts:
      - "no-new-privileges:true"
    pids_limit: 200
    read_only: false
    tmpfs:
      - "/tmp"
    volumes:
      - "{{ mattermost_data_directory }}/config:/mattermost/config:rw"
      - "{{ mattermost_data_directory }}/data:/mattermost/data:rw"
      - "{{ mattermost_data_directory }}/logs:/mattermost/logs:rw"
      - "{{ mattermost_data_directory }}/plugins:/mattermost/plugins:rw"
      - "{{ mattermost_data_directory }}/client/plugins:/mattermost/client/plugins:rw"
      - "{{ mattermost_data_directory }}/bleve-indexes:/mattermost/bleve-indexes:rw"
    env:
      TZ: "{{ timezone }}"
      MM_SQLSETTINGS_DRIVERNAME: "postgres"
      MM_SQLSETTINGS_DATASOURCE: "postgres://{{ mattermost_db_user }}:{{ mattermost_db_password }}@mattermost-db:5432/mattermost?sslmode=disable&connect_timeout=10"
      MM_BLEVESETTINGS_INDEXDIR: "/mattermost/bleve-indexes"
      MM_SERVICESETTINGS_SITEURL: "https://mm.{{ tunnel_domain_name }}"
    restart_policy: unless-stopped
