ingress:
  - hostname: "echo-server.{{ tunnel_domain_name }}"
    service: http://echo-server:8080

  - hostname: "vaultwarden.{{ tunnel_domain_name }}"
    service: http://bitwarden:80

  - hostname: "vaultwarden.{{ tunnel_domain_name }}/notifications/hub"
    service: http://bitwarden:3012

  - hostname: "shiori.{{ tunnel_domain_name }}"
    service: http://shiori:8080

  - hostname: "navidrome.{{ tunnel_domain_name }}"
    service: http://navidrome:4533

  # - hostname: "nextcloud.{{ tunnel_domain_name }}"
  #   service: http://nextcloud:80

  # - hostname: "bookstack.{{ tunnel_domain_name }}"
  #   service: http://bookstack:80

  # - hostname: "sd.{{ tunnel_domain_name }}"
  #   service: http://192.168.50.4:7860

  - service: http_status:404
