ingress:
  - hostname: "echo-server.{{ cloudflared_tunnel_domain_name }}"
    service: http://echo-server:8080

  - hostname: "siyuan.{{ cloudflared_tunnel_domain_name }}"
    service: http://siyuan:6806

  - hostname: "siyuan.{{ cloudflared_tunnel_domain_name }}/ws"
    service: http://siyuan:6806

  - service: http_status:404
