ingress:
  # - hostname: "traefik.{{ tunnel_domain_name }}"
  #   service: https://traefik.{{ domain_name }}

  - hostname: "echo-server.{{ tunnel_domain_name }}"
    service: http://echo-server:8080

  - hostname: "vaultwarden.{{ tunnel_domain_name }}"
    service: http://bitwarden:80

  - hostname: "vaultwarden.{{ tunnel_domain_name }}/notifications/hub"
    service: http://bitwarden:3012

  - hostname: "shiori.{{ tunnel_domain_name }}"
    service: http://shiori:8080

  - hostname: "navidrome.{{ tunnel_domain_name }}"
    service: http://navidrome:4533

  - hostname: "memos.{{ tunnel_domain_name }}"
    service: http://memos:5230

  - hostname: "immich.{{ tunnel_domain_name }}"
    service: http://immich-proxy:8080

  - hostname: "homepage.{{ tunnel_domain_name }}"
    service: http://homepage:3000

  - hostname: "miniflux.{{ tunnel_domain_name }}"
    service: http://miniflux:8080

  - hostname: "mm.{{ tunnel_domain_name }}"
    service: http://mattermost:8065

  - hostname: "ha.{{ tunnel_domain_name }}"
    service: http://homeassistant:8123

  # - hostname: "chat.{{ tunnel_domain_name }}"
  #   service: http://rocketchat:3000

  # - hostname: "nextcloud.{{ tunnel_domain_name }}"
  #   service: http://nextcloud:80

  # - hostname: "bookstack.{{ tunnel_domain_name }}"
  #   service: http://bookstack:80

  # - hostname: "sd.{{ tunnel_domain_name }}"
  #   service: http://192.168.50.4:7860

  - service: http_status:404
