---
prometheus_enabled: true
prometheus_version: 2.46.0
prometheus_web_external_url: "http://192.168.50.3:9090"
prometheus_alertmanager_config:
  - scheme: http
    static_configs:
      - targets: ["localhost:9093"]
prometheus_storage_retention: "7d"
prometheus_config_flags_extra:
  web.enable-lifecycle: ""
prometheus_targets:
  node:
    - targets:
      - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9100"
      labels:
        env: personal
  cadvisor:
    - targets:
      - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9280"
      labels:
        env: personal
prometheus_scrape_configs:
  - job_name: "prometheus"
    metrics_path: "{{ prometheus_metrics_path }}"
    static_configs:
      - targets:
          - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090"
  - job_name: "node"
    file_sd_configs:
      - files:
          - "{{ prometheus_config_dir }}/file_sd/node.yml"
  - job_name: "cadvisor"
    file_sd_configs:
      - files:
          - "{{ prometheus_config_dir }}/file_sd/cadvisor.yml"
