---
prometheus_enabled: true
prometheus_version: 2.46.0
prometheus_web_external_url: "http://192.168.50.3:9090"
prometheus_alertmanager_config:
  - scheme: http
    static_configs:
      - targets: ["b550m:9093"]
prometheus_storage_retention: "7d"
prometheus_config_flags_extra:
  web.enable-lifecycle: ""
