---
- name: Create Traefik Directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: kchou
    group: kchou
    mode: "0755"
    state: directory
  with_items:
    - "{{ traefik_data_directory }}"
    - "{{ traefik_data_directory }}/letsencrypt"

- name: Traefik Docker Container
  community.docker.docker_container:
    name: traefik
    image: traefik:v2.10.3
    networks:
      - name: homelab
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email={{ acme_email }}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    volumes:
      - "{{ traefik_data_directory }}/letsencrypt:/letsencrypt:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    env:
      CF_API_EMAIL: "{{ cloudflare_email }}"
      CF_API_KEY: "{{ cloudflare_api_key }}"
    restart_policy: unless-stopped

- name: Create whoami Container
  community.docker.docker_container:
    name: whoami
    image: traefik/whoami
    networks:
      - name: homelab
    labels:
      traefik.enable: "true"
      traefik.http.routers.whoami.rule: "Host(`whoami.{{ domain_name }}`)"
      traefik.http.routers.whoami.entrypoints: "websecure"
      traefik.http.routers.whoami.tls.certresolver: "myresolver"
      traefik.http.services.whoami.loadbalancer.server.port: "80"
