---
- name: Create Syncthing Directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0777"
  with_items:
    - "{{ syncthing_data_directory }}"

- name: Create Syncthing Directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ syncthing_config_directory }}"

- name: Syncthing Docker Container
  community.docker.docker_container:
    name: syncthing
    image: syncthing/syncthing:1.23.7
    networks:
      - name: homelab
    ports:
      - "8384:8384"
      - "22000:22000"
      - "22000:22000/udp"
      - "21027:21027/udp"
    volumes:
      - "{{ syncthing_config_directory }}:/var/syncthing"
      - "{{ syncthing_data_directory }}:/syncthing"
    env:
      PUID: "1000"
      PGID: "1000"
    # labels:
    #   traefik.enable: "true"
    #   traefik.http.routers.syncthing.rule: "Host(`syncthing.{{ domain_name }}`)"
    #   traefik.http.routers.syncthing.entrypoints: "websecure"
    #   traefik.http.routers.syncthing.tls.certresolver: "myresolver"
    #   traefik.http.routers.syncthing.tls.domains[0].main: "{{ domain_name }}"
    #   traefik.http.routers.syncthing.tls.domains[0].sans: "*.{{ domain_name }}"
    #   traefik.http.services.syncthing.loadbalancer.server.port: "8384"
    restart_policy: unless-stopped
