---
- name: Create Bitwarden Directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ bitwarden_data_directory }}"

- name: Bitwarden Docker Container
  community.docker.docker_container:
    name: bitwarden
    image: vaultwarden/server:1.28.1
    networks:
      - name: homelab
    volumes:
      - "{{ bitwarden_data_directory }}:/data"
    env:
      DOMAIN: "https://vaultwarden.{{ domain_name }}"
      SIGNUPS_ALLOWED: "{{ bitwarden_allow_signups | string }}"
      LOG_FILE: "/data/access.log"
      WEBSOCKET_ENABLED: "true"
    restart_policy: unless-stopped

- name: Bitwarden Backup Container
  community.docker.docker_container:
    name: vaultwarden-backup
    image: bruceforce/vaultwarden-backup:2.0.1
    restart_policy: unless-stopped
    volumes_from: bitwarden
